### ISSUE TITLE
Port Extension to Firefox

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/find#127]
## Issue Description
To increase the reach of our extension, it would be great if it were made available to Firefox users. For the most part, the API for Firefox is identical  thanks to the Mozilla Polyfill. So, making our extension compatible with Firefox should require little modification to the repository.

The goal is to avoid making seperate copies of the repository for chrome and firefox. Adding a condition at the top of the scripts to chose either the `chrome` or `browser` namespace is ideal.

## Tasks
- [ ] Implement changes necessary to enable extension on both chrome and firefox
- [ ] Redesign UI to mimic Firefox Find-in-Page tool
- [ ] Investigate deployment steps for Firefox
- [ ] Document

## Screenshots and Documentation
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs
