### ISSUE TITLE
Support Text Boundaries for Elements with Alternate Display Properties

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/find#152]
## Issue Description
Currently, an element is considered to be inline if it appears in a list of elements that have a default inline property. This is problematic because it is possible to override the default behavior using the `display` property. 

Although the extension works pretty well in most cases, it is important to ensure that the extension is also compatible with alternate display styles.

## Steps to Reproduce
- Create an HTML document like the following:

```
<div>
	test text
	<span style="display: block;">Test</span>
</div>
```

- This is rendered

> test text
> Test

- Searching `test text Test` in the extension will yield a single occurrence, when it shouldn't.

## Tasks
- [ ] determine which display properties will force the element into a block box, and which will not.
- [ ] implement a function that uses the `display` style property to determine if element should be treated as block or inline
- [ ] handle edge cases (e.g. inherit)

## Screenshots and Documentation
[Detailed list of Display Properties] (https://developer.mozilla.org/en-US/docs/Web/CSS/display)
