### ISSUE TITLE
Publish the user guide online or as a setting

### ISSUE THREAD

**Issue by Madis0** [brandon1024/find#301]
## Issue Description
Find+ has an user guide, however it is only accessible through a right click on the button itself. I suggest making it more exposed for it to be useful to the users.

## Steps to Reproduce
N/A

## Tasks
- [ ] Make it an options page #197
- [ ] Publish it online (instead of the wiki?)
- [ ] Add a button for it inside extension settings panel

## Screenshots and Documentation
See `moz-extension://b3e61955-8666-4aeb-9f1e-e8c6ae1fadd5/popup/help.html` or `chrome-extension://fddffkdncgkkdjobemgbpojjeffmmofb/popup/help.html`

**Comment by brandon1024** [comment]
Great ideas! I used to use GitHub pages, but at the time it wasn't working well for me, but I could possibly reuse the current help page and host it through GitHub pages. I'll investigate and update!

**Comment by muescha** [comment]
also: add a link to the help page in the options dialog
