### ISSUE TITLE
More Omnibox features

### ISSUE THREAD

**Issue by Madis0** [brandon1024/find#303]
## Issue Description
It's nice that we can use Find+ from the Omnibox, but it should have a little more parity with the main box.

## Tasks
- [ ] Actions next, previous, close (unhighlight)
- [ ] Count of items found
- [ ] Errors (internal pages, iframes)
- [ ] Results (when implementing #268)

**Comment by brandon1024** [comment]
The omnibox has a very limited functionality, and I'm not sure how I could implement the features you requested. Could you give more details?

I enabled omnibox support as a way to find occurrences quickly. It was never designed to replace the extension popup.

**Comment by Madis0** [comment]
Well, the Omnibox API supports [suggestResult](https://developer.chrome.com/extensions/omnibox#type-SuggestResult), so think that could be used to add additional data (count, errors) and actions (next, previous, close).

**Comment by brandon1024** [comment]
@Madis0, I've been playing around with the omnibox API and I can't find an elegant way to implement some of the features you requested. It's easy enough to show occurrence count and report errors (i'll be opening a PR for that shortly), but implementing actions in the omnibar is a bit hacky and I anticipate confusion if that was merged in. So for now, I'll only implement count and error reporting.

**Comment by Madis0** [comment]
What if you added real phrases from the page as a suggestion, similar to this extension https://chrome.google.com/webstore/detail/spot-better-find-in-page/bbpdiffmmobnnngmfigpgddgjpgjgbol

**Comment by Madis0** [comment]
Oops, forgot what I said previously. Could you at least add the "unhighlight" bit when the user selects either of the options?

**Comment by brandon1024** [comment]
I'm not sure I follow, what do you mean by "selects either of the options"?

**Comment by Madis0** [comment]
I was referring to this 
> So for now, I'll only implement count and error reporting.
so clicking either counter or error would just disregard the search.

**Comment by brandon1024** [comment]
Ahh ok, yes that's how it works as implemented. You're welcome to pull down my changes [here](https://github.com/brandon1024/find/pull/330) and try it, wouldn't hurt to have a second opinion on these changes.

**Comment by Madis0** [comment]
Right now tested on Edgium and the counter works, but clicking it does nothing. Not seeing any errors on iframe pages either (while it correctly shows a warning triangle on find+ popup).

**Comment by brandon1024** [comment]
That's right, clicking it will have no effect. Typically the omnibox is used to suggest search results, and clicking a suggestion will just populate text in the box. There's nothing to populate in the omnibox when displaying counts, so this will have no effect.

At first, I thought reporting iframes would be a bit tricky to do but it might be easier than I anticipated. Will update.
