### ISSUE TITLE
Some styles escape extension popup and are applied on web pages.

### ISSUE THREAD

**Issue by stefanbols** [brandon1024/find#364]
## Issue Description
Some styles escape extension popup and are applied on web pages. It may be regarding icons. But I/you will need to investigate.

## Steps to Reproduce
- Go to [background.js](../blob/develop/background/background.js) in this repo
- Pay attention to the "Watch/Star/Fork" in the top right of the Github web page
- Open the "popup" of Find+
- See that padding or margins are changed for something in the labels or icons of each item.

## Tasks
- [ ] Investigate which styles are escaping
- [ ] Introduce CSS fix which contains style inside of extension
- [ ] (optional) Make so all classes are under a unique class. For example prefix all classes with : `.find-ext`

## Screenshots and Documentation
![image](https://user-images.githubusercontent.com/7382502/136337851-44bd4a43-9a67-402b-ba76-0307f6978af2.png)
