### ISSUE TITLE
Build Out Backend DOM Search

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/find#9]
Build the javascript framework for searching the DOM for a regex.

Tasks:
- [X] Create a framework allowing the extension to communicate with the web page.
- [X] Add jQuery and jQuery UI to lib folder
- [X] Create a background script, connected to the popup through a long-lived connection, that will handle most of the business logic behind the extension.
- [x] Build a script to parse the webpage into pieces of text with references to the webpage DOM, allowing the background script to search through the text and highlight text on the page.
- [X] Create endpoints in background script to hand over information to highlighter for highlighting text on the web page.
- [X] Popup UI fixes and improvements
- [X] Add support for remote and local text files
- [x] Complete Highlighter script.
- [x] Final code refactor.
- [x] Dev testing to iron out small issues
- V2: Show occurrences for visible text only

**Comment by brandon1024** [comment]
How to make this work:

`index.js` <--> `backend.js` <--> `content.js` --> `highlight.js`

Update: when the regex search field sees a keypress event, the update function is called. The update function removes all previous highlights from the page, parses the DOM for matching text, and highlights all occurrences of the specified regex. The first occurrence is highlighted in a brighter color, and is selected in the page.

Next: select the next occurrence. Removes the highlight from the previous occurrence, and adds it to the next one.

Previous: select the previous occurrence.

Close: Close the popup. Remove all highlights from the page.

**Comment by brandon1024** [comment]
I looked into this issue, and the implementation might be more complicated than it seems. Using the DOM solely for highlighting and and searching won't be feasible. We may need to implement some kind of rule engine to build a model of the webpage that we can use to search and inject html markup.

If we want to support searching through plain text files, for instance, where no DOM exists, we will need find a way to inject and remove the markup.

We will also need to handle cases where text is spread between multiple DOM elements. For example:

```
<div>
     some text
     <span style="blah">that has style</span>
</div>
```

This will render as a single line of text, but is split over multiple elements. It can get pretty complicated to highlight `some text that`. We would need to modify the HTML to this:

```
<div>
     <span style="highlight">
          some text
          <span style="blah">that</span>
     </span>
     <span style="blah"> has style</span>
</div>
```

**Comment by MikeWalz11** [comment]
The last step requiring js to highlight text should be "done".  The only issue remaining after the parsing is completed would be to tweak the existing highlight.js

**Comment by brandon1024** [comment]
@MikeWalz11 It might require some pretty heavy modifications though. I have't really looked into it much yet, but once I finish the rest, you can dive into it!

**Comment by brandon1024** [comment]
Finally seeing some progress!

![image](https://cloud.githubusercontent.com/assets/22732449/25300965/b52877de-26e9-11e7-8b9f-52927058dcfc.png)

**Comment by brandon1024** [comment]
Progress: https://github.com/brandon1024/find/compare/develop...F9-Build-Backend-DOM-Search

**Comment by MikeWalz11** [comment]
PR Merged: #55
